### ISSUE TITLE
withCredentials property missing

### ISSUE THREAD

**Issue by klinem** [pretenderjs/FakeXMLHttpRequest#11]
I'm using ember-cli-mirage and trying to use mapbox.js inside the project. Mapbox is doing a check for the `withCredentials` property for IE support:

``` javascript
var x = new window.XMLHttpRequest();

if (cors && !('withCredentials' in x)) {
  x = new window.XDomainRequest();
  ...
}
```

Because `withCredentials` is missing from the FakeXMLHttpRequest this fails outright. I understand Pretender.js added CORS support so would this fall inline with that?

**Comment by grzegorz-dubicki** [comment]
+1
