### ISSUE TITLE
Set-Cookie Header Ignored

### ISSUE THREAD

**Issue by ronco** [pretenderjs/FakeXMLHttpRequest#18]
Is there any reason why the `Set-Cookie` header is being explicitly ignored [here](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/src/fake-xml-http-request.js#L343) and [here](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/src/fake-xml-http-request.js#L343)?  I'd love to simulate a login flow with using pretender to save a faux auth cookie.

**Comment by bantic** [comment]
@ronco Good question. This is part of the XHR spec to prevent ajax requests from reading cookies for security reasons. If the cookie was allowed to be set it would be available (when doing a "real" ajax request) in `document.cookie` later, but it's [forbidden by the spec](http://www.w3.org/TR/XMLHttpRequest/#the-getresponseheader()-method) to read the value of the "Set-Cookie" or "Set-Cookie2" header:
```
3. If header is a case-insensitive match for Set-Cookie or Set-Cookie2, return null.
```

**Comment by ronco** [comment]
Hey @bantic, Thanks for the answer.  I figured it was probably a security restriction.  Definitely a bummer, but understandable.

**Comment by bantic** [comment]
@ronco I think you could fake out the setting of the cookie in the xhr response, though, `document.cookie=myFakeAuthCookie;`

**Comment by ronco** [comment]
@bantic Great minds think alike.  That's actually the approach I took and I also submitted a [DOC PR](https://github.com/samselikoff/ember-cli-mirage/pull/304) to ember-cli-mirage with an example of doing just this.
