### ISSUE TITLE
After the latest release fetching of json files results in `responseText` to be the response string and the `response` field to be null

### ISSUE THREAD

**Issue by VictorSoroka1** [pretenderjs/FakeXMLHttpRequest#54]

**Comment by kellyselden** [comment]
I thought `response` was a previously unused property. Are you saying it used to be populated with something?

**Comment by VictorSoroka1** [comment]
Yes, we use it in combination with `whatwg-fetch` for testing. The thing is that `whatwg-fetch` relies on the response field. https://github.com/github/fetch/blob/master/fetch.js#L462

**Comment by kellyselden** [comment]
What were the two properties set to before the change?

**Comment by VictorSoroka1** [comment]
## Before the change
<img width="1010" alt="Screen Shot 2019-11-28 at 17 39 03" src="https://user-images.githubusercontent.com/40821852/69818809-3fefb800-1206-11ea-8551-6d56476f7dfb.png">

## After the change (basically now)
<img width="1010" alt="Screen Shot 2019-11-28 at 17 20 59" src="https://user-images.githubusercontent.com/40821852/69818808-3fefb800-1206-11ea-8163-a7513829ff34.png">

Basically, the issue for me is that now the expression below
`var body = 'response' in xhr ? xhr.response : xhr.responseText;` evaluates to the `xhr.response` even though it is `null`.

**Comment by VictorSoroka1** [comment]
As I see the issue is that if `response` is not being copied by Pretender

https://github.com/pretenderjs/pretender/blob/master/src/index.ts#L116

after the call there

https://github.com/pretenderjs/pretender/blob/master/src/index.ts#L159

So even in your code, you update them both, the _Pretender_ does not update them accordingly and thus `response` field will always be null at the end in my case.

**Comment by kellyselden** [comment]
It looks like it needs this code to be correct https://github.com/pretenderjs/pretender/pull/280

**Comment by VictorSoroka1** [comment]
Yeah.

**Comment by VictorSoroka1** [comment]
@cowboyd, as I see https://github.com/thefrontside/bigtest/tree/master/packages/mirage is archived now. Will it be possible after the pretenderjs/pretender#280 is merged to update the dependency to it?

**Comment by xg-wang** [comment]
@VictorSoroka1 just released https://github.com/pretenderjs/pretender/releases/tag/v3.1.0.
Can you try upgrade it?

**Comment by cowboyd** [comment]
@VictorSoroka1 Sorry, I'm not sure I follow. We archived that packages since https://github.com/miragejs/mirage is now a thing. I'm happy to do whatever, but not understanding quite what that is :)

**Comment by xg-wang** [comment]
Closing https://github.com/pretenderjs/pretender/issues/283 means this should be fixed. Pretender is detecting a previously non-existed feature of fake-xml-http-request therefore breaking the semver. @VictorSoroka1 can we close?

**Comment by VictorSoroka1** [comment]
Thank you for the additional release.
